USE tempdb
ALTER DATABASE Caso01_DB2_Esteban SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
DROP DATABASE IF EXISTS Caso01_DB2_Esteban 
GO
CREATE DATABASE Caso01_DB2_Esteban 
GO
USE Caso01_DB2_Esteban 

--Create tables

CREATE TABLE PROVINCE(
  province_id INT IDENTITY(1,1) PRIMARY KEY,
  name NVARCHAR(100) NOT NULL UNIQUE
)

CREATE TABLE CANTON(
  canton_id INT IDENTITY(1,1) PRIMARY KEY,
  name NVARCHAR(250) NOT NULL,
  province_id INT NOT NULL FOREIGN KEY REFERENCES PROVINCE(province_id)
)

CREATE TABLE USER_TYPE(
  user_type_id INT IDENTITY(1,1) PRIMARY KEY,
  user_type_name NVARCHAR(100) NOT NULL UNIQUE
)

CREATE TABLE KPI_TYPE(
  kpi_id INT IDENTITY(1,1) PRIMARY KEY,
  kpi_name NVARCHAR(100) NOT NULL UNIQUE
)

CREATE TABLE PARTY(
  party_id INT IDENTITY(1,1) PRIMARY KEY,
  name NVARCHAR(250) NOT NULL UNIQUE,
  flag NVARCHAR(500) NOT NULL UNIQUE,
  creation_date SMALLDATETIME NOT NULL,
  foundation DATE,
)

CREATE TABLE PERSON(
  person_id INT IDENTITY(1,1) PRIMARY KEY,
  name NVARCHAR(250) NOT NULL,
  lastname NVARCHAR(250) NOT NULL,
  birthdate DATE, 
  id INT NOT NULL UNIQUE,
  photo NVARCHAR(500),
  creation_date SMALLDATETIME NOT NULL,
  canton_id INT NOT NULL FOREIGN KEY REFERENCES CANTON(canton_id)
)

CREATE TABLE EMAIL(
  email_id INT IDENTITY(1,1) PRIMARY KEY,
  email NVARCHAR(250) NOT NULL UNIQUE,
  person_id INT NOT NULL FOREIGN KEY REFERENCES PERSON(person_id)
)

CREATE TABLE PHONE(
  phone INT PRIMARY KEY,
  person_id INT NOT NULL FOREIGN KEY REFERENCES PERSON(person_id)
)

CREATE TABLE USER_X_TYPE(
  id INT IDENTITY(1,1) PRIMARY KEY,
  person_id INT NOT NULL FOREIGN KEY REFERENCES PERSON(person_id),
  user_type_id INT NOT NULL FOREIGN KEY REFERENCES USER_TYPE(user_type_id)
)

CREATE TABLE USER_X_GROUP(
  id INT IDENTITY(1,1) PRIMARY KEY,
  person_id INT NOT NULL FOREIGN KEY REFERENCES PERSON(person_id),
  party_id INT NOT NULL FOREIGN KEY REFERENCES PARTY(party_id)
)

CREATE TABLE PLAN_PARTY(
  plan_id INT IDENTITY(1,1) PRIMARY KEY,
  title NVARCHAR(150) NOT NULL,
  description_plan NVARCHAR(250),
  party_id INT NOT NULL FOREIGN KEY REFERENCES PARTY(party_id),
  publish_date DATE NOT NULL,
)

CREATE TABLE ACTION_PLAN(
  action_id INT IDENTITY(1,1) PRIMARY KEY,
  action_name NVARCHAR(150) NOT NULL,
  action_description NVARCHAR(2000), 
  plan_id INT NOT NULL FOREIGN KEY REFERENCES PLAN_PARTY(plan_id)
)

CREATE TABLE DELIVERABLES(
  deliverable_id INT IDENTITY(1,1) PRIMARY KEY,
  action_id INT NOT NULL FOREIGN KEY REFERENCES ACTION_PLAN(action_id),
  plan_id INT NOT NULL FOREIGN KEY REFERENCES PLAN_PARTY(plan_id), 
  canton_id INT NOT NULL FOREIGN KEY REFERENCES CANTON(canton_id),
  kpi_value INT NOT NULL,
  kpi_type INT NOT NULL FOREIGN KEY REFERENCES KPI_TYPE(kpi_id),
  post_time DATE NOT NULL
)